export default {
  container: {
    backgroundColor: "#FFF",
  },
  bgc:{
    backgroundColor:'#4a81f8',
    shadowColor:'#000'
  },
  fontc:{
    color:'#999'
  },
  imgSize:{
    width:250,
    height:250
  },
  text:{
      textAlign:'center',
      marginBottom:'40'
  },
  ItemStyle:{
    marginLeft:20,
    marginRight:20
  },
  input:{
    color:'#999',
  },
   btn:{
    margin:30,
    borderRadius:15,
    backgroundColor:'#4a81f8'
  },
    btnV:{
        margin:0,
        borderRadius:14,
        width:120,
        marginTop:4,
        height:40,
        backgroundColor:'#4a81f8'
    },
  btnSend:{
    backgroundColor:'#4a81f8',
  },
  mt:{
    marginTop:50,
  },
}
